on:
  push:
    branches:
      - somiasrour
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
	- uses: actions/checkout@v3
        run: docker login --username somiasrour --password dckr_pat_aH-cs6gV5nI1HJ9PQDGnJKKq9aM